env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb
  - plugin:flowtype/recommended
plugins:
  - flowtype
rules:
  semi:
    - error
    - never
settings:
  import/resolver:
    babel-module: {}
