env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb
  - plugin:flowtype/recommended
plugins:
  - flowtype
rules:
  react/sort-comp:
    - 2
    - order:
      - type-annotations
      - static-methods
      - everything-else
      - lifecycle
      - /^on.+$/
      - rendering
      groups:
        rendering:
          - /^render.+$/
          - render
  semi:
    - error
    - never
settings:
  import/resolver:
    babel-module: {}
